// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace File_Differ
{
    internal sealed partial class Vsix
    {
        public const string Id = "e4f66399-313b-499d-9fe1-51a4004e9d01";
        public const string Name = "File_Differ";
        public const string Description = @"The easiest way to diff file directly from Solution Explorer.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Yed";
        public const string Tags = "";
    }
}
