// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DesignerDiffer
{
    internal sealed partial class Vsix
    {
        public const string Id = "e4f66399-313b-499d-9fe1-51a4004e9d01";
        public const string Name = "Designer-Differ";
        public const string Description = @"The easiest way to sort windows form designer generated code, to diff files and windows form designer file with git history directly from Solution Explorer.";
        public const string Language = "en-US";
        public const string Version = "1.0.0";
        public const string Author = "Yed";
        public const string Tags = "";
    }
}
