// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace DesignerDiffer
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidFile_VSPackageString = "717f3e2d-aaf6-486c-add8-fa6228f4d907";
        public static Guid guidFile_VSPackage = new Guid(guidFile_VSPackageString);

        public const string guidFile_VSPackageCmdSetString = "020df2a1-db50-4da9-b02d-429321000270";
        public static Guid guidFile_VSPackageCmdSet = new Guid(guidFile_VSPackageCmdSetString);

        public const string guidImagesString = "2a122da1-1d9a-48b8-89ff-ee6527567153";
        public static Guid guidImages = new Guid(guidImagesString);

        public const string guidImages1String = "ed02defe-f3bf-4cf7-913b-9772fffe8e26";
        public static Guid guidImages1 = new Guid(guidImages1String);

        public const string guidImages2String = "1dd321f2-63ba-4bff-aee8-6f6d3995c650";
        public static Guid guidImages2 = new Guid(guidImages2String);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int FileContextMenuGroup = 0x0110;
        public const int EditorContextMenuGroup = 0x0120;
        public const int DiffFilesCommandId = 0x0100;
        public const int CompareHistoryCommandId = 0x0101;
        public const int DiffContentCommandId = 0x0102;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0001;
        public const int bmpPic3 = 0x0001;
    }
}